services:

  dolibarr:
    image: dolibarr/dolibarr:latest
    container_name: dolibarr
    environment:
      DOLI_DB_HOST: "mysql"
      DOLI_DB_HOST_PORT: "3306"
      DOLI_DB_USER: "dolibarr"
      DOLI_DB_PASSWORD: "p4ssw0rd"
      DOLI_DB_NAME: "dolibarr"
      DOLI_ADMIN_LOGIN: "admin"
      DOLI_ADMIN_PASSWORD: "p4ssw0rd"
    ports:
      - "8200:80"
    restart: unless-stopped
    links:
      - mysql    
    volumes:
      - ./dolibarr-docs:/var/www/documents
      - ./dolibarr-custom:/var/www/html/custom

  mysql:
    image: mariadb:latest
    container_name: dolibarr-db
    environment:
      MYSQL_DATABASE: "dolibarr"
      MYSQL_USER: "dolibarr"
      MYSQL_PASSWORD: "p4ssw0rd"
      MYSQL_ROOT_PASSWORD: "p4ssw0rd"
    restart: unless-stopped
    volumes:
      - ./mysql-data:/var/lib/mysql
    
